# Generated by Django 3.1.6 on 2021-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Short_text',
            field=models.TextField(default='тут короткий текст', max_length=75),
        ),
    ]
