# Generated by Django 3.1.6 on 2021-03-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_maker', '0002_post_short_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_for_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
