# Generated by Django 3.1.6 on 2021-05-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_maker', '0004_auto_20210306_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data',
            new_name='date',
        ),
    ]
