# Generated by Django 3.1.6 on 2021-05-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_maker', '0008_auto_20210525_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='published',
        ),
        migrations.AddField(
            model_name='post',
            name='Short_text',
            field=models.TextField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='img_for_post',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
